#! /bin/sh

sxhkd &

bspc monitor -d >_ 

feh --bg-fill ~/gits/my_suckless_conf/wp3.jpg &
polybar-msg cmd restart

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color		"#000000"
bspc config active_border_color		"#484848"
bspc config focused_border_color	"#484848"
bspc config presel_feedback_color	"#141414"
